/**
 * Types for the behavioral index entries.
 * The behavioral index is generated by the Claude Code agent — see the ee skill.
 */

export type ImplicitIntentCategory =
  | "hesitation"
  | "coordination"
  | "attention"
  | "smoothness";

export interface ImplicitIntentInstance {
  category: ImplicitIntentCategory;
  taskSet: string[];
  startSec: number;
  endSec: number;
  features: Record<string, number>;
  score: number;
  reasoning: string;
}

export interface SegmentResult {
  segmentIndex: number;
  startSec: number;
  endSec: number;
  activity: string;
  taskTypeSequence: string[];
  implicitIntents: ImplicitIntentInstance[];
}

export interface BehavioralVideoEntry {
  videoId: string;
  videoName: string;
  generatedAt: string;
  segments: SegmentResult[];
}
